### ISSUE TITLE
[Bug] Controller is detected but inputs are not on Mac.

### ISSUE THREAD

**Issue by kiradotlgbt** [isXander/Controlify#135]
### Current Behaviour

The controller is detected, but when I try to actually do anything in game (or use the vibration tester) it doesnt work. Controllers work on other programs and games. Tried on PS4 and Switch Pro controllers.

### Expected Behaviour

I expected the inputs to be detected :D

### Screenshots

<img width="621" alt="image" src="https://github.com/isXander/Controlify/assets/136995679/ce3a1256-9681-4b74-881e-83cfb5c8432c">

### Reproduction Steps

1. Pair a controller up with your Mac
2. Try playing Minecraft
3. Realise it doesnt work :(

### Mod Version

1.4.4+1.20

### Controller

Nintendo Switch Pro Controller + PS4 Controller

### Bluetooth

- [X] Yes

### Operating System

macOS

### ARM

- [X] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by isXander** [comment]
Switch Pro is notoriously bad with Controlify. Don't have one to test, but will leave this open.

**Comment by kiradotlgbt** [comment]
Are PS4/Xbox One controllers supposed to work better? They don't seem to work either..

**Comment by caleb39411** [comment]
I am having the same issue with a DualSense, the only thing that works is vibration.

**Comment by SpektacleFR** [comment]
Same issues as OP with my Xbox Series X/S Controller.  Issues persist in 1.4.6+1.20.  Also this is a duplicate of #101

**Comment by Arenovas** [comment]
Since it seems to be a similar problem, I can't seem to use any controller on my Windows 10 PC in version 1.5.0. Tested a wireless 360 controller and my 8BitDo SN30 Pro controller in it's Xinput, Dinput, MacOS/dualshock, and Switch Pro modes and they all didn't work but were detected.
And to note, all the controllers I tested worked in 1.4.6.

**Comment by kiradotlgbt** [comment]
Personally it seems to have been fixed with the latest update.

**Comment by SpektacleFR** [comment]
After updating my SDL2 version, it appears as though my Xbox Series X/S Controller is being recognized as a joystick, which may be why the unknown controller dialogue does not show up for me.  I have tried purging the Controlify-natives folder as well as the controlify config file.

**Comment by Wionsito** [comment]
The same happens to me, also macOS arm

**Comment by SpektacleFR** [comment]
Fully reinstalled MacOS Ventura 13.5.1 today.  Will attempt another test later and I'll update then.

**Comment by SpektacleFR** [comment]
Update: Newest version downloaded, same situation.  No improvements or change, Xbox Series X/S controller still recognized as a joystick and no default bindings are assigned.  Triggers still do not detect input.

**Comment by lunarlullaby05** [comment]
I had gotten my Xbox One controller to work on my Mac with the key bindings through the mod, and it was working great for about two months, until I just updated it to the newest update of this mod...now, it's constantly giving me the "controller disconnected" or whatever message. I've attached it to this message. 

Again--the mod had worked perfectly until the newest update of the mod. 

<img width="1440" alt="Screenshot 2024-04-18 at 5 50 16 PM" src="https://github.com/isXander/Controlify/assets/167483568/636271f4-218d-48b0-828a-5881a86cb3b2">

**Comment by isXander** [comment]
What version are you on?

**Comment by lunarlullaby05** [comment]
sorry for the late reply--I'm on 1.20.4 of minecraft and last tried the mod last on 2.0.0-beta.3. i see there's been some updates since I commented, so I'll try it again quick

**Comment by lunarlullaby05** [comment]
It's working now!! thank you :)
