### ISSUE TITLE
[Bug] Can't break blocks out of focus after opening any GUI

### ISSUE THREAD

**Issue by adcar** [isXander/Controlify#436]
### Current Behaviour

Likely related to #384. I can't break any blocks when out of focus after opening any GUI.

### Expected Behaviour

Breaking blocks when out of focus

### Reproduction Steps

1. Enable Out of Focus Input
2. Move the focus to another window
3. Open up the inventory and close it, then try breaking a block

### Mod Version

Beta 17. Minecraft 1.21.1

### Controller

issues

### Bluetooth

- [X] Yes

### Operating System

Linux/SteamOS

### ARM

- [ ] Yes

### Just to make sure...

- [X] I have made sure I am using the latest version of Controlify for the latest version of Minecraft.
- [X] I have made sure there are no other issues describing the same problem on the [issue tracker](https://github.com/isXander/Controlify/issues).

**Comment by VioletMaze** [comment]
Also experiencing this issue on Windows 10 x64. Running Fabric 1.21.0 on the Prism Launcher, Controlify Beta 17. I open two instances of the game in separate windows in splitscreen fashion. The out-of-focus window cannot break blocks which require the right trigger to be held down, even with the out of focus input setting enabled. Instant-break blocks (eg. tall grass) can be broken. It is definitely a Controlify issue, it persists without any other mods other than minimum dependencies. I cannot use beta 18 or beta 19 due to Issue #437 , which forces me to use beta 17 or lower, so cannot confirm if it has been fixed in a later version. I'll try running older betas tomorrow to see if this behaviour was introduced in a previous version.

**Comment by VioletMaze** [comment]
MidnightControls has the same issue as Controlify, out of focus windows cannot mine after opening any GUI. However, in Midnight, turning on the virtual mouse fixes the issue entirely. This makes me think it is to do with having the LMB's "off" state overriding the LTrigger's "on" state, reading from both controller and KB&M.

**Comment by AvacynPhyrexian** [comment]
Is there any word on this being fixed for 1.20.1?

**Comment by AvacynPhyrexian** [comment]
This has been resolved in todays patch FYI

**Comment by AvacynPhyrexian** [comment]
Can be closed just tested

**Comment by VioletMaze** [comment]
I don't see how this update affects this issue, maybe some kind of GUI clash with sodium? I'll test it later and see if it works

**Comment by kimpoliini** [comment]
I just tested and the problem still persists on Fabric 1.20.1

**Comment by VioletMaze** [comment]
This issue is not resolved. Tested on two new instances with minimum dependencies, 1.21.0. Did not change any settings apart from enabling out of focus input on both. This bug is still present.

**Comment by thesaltan1312** [comment]
Confirmed I am still experiencing the bug as well on the latest version of Controlify for 1.20.1

**Comment by dashleysmith** [comment]
Additional observations (win 11, MultiMC, Minecraft 1.20.1, Fabric):

Running command `/gamemode survival` fixes the issue temporarily (until the next time you open your inventory). Other ways to change gamemode don't seem to help. i.e. the controlify gamemode switcher doesn't have the same effect.

**Comment by walczi6** [comment]
Hey guys, 
I think I’ve found some temporary solution. At least it helped in my case.
Since the problem lies in the operation of inactive applications, you need to download a program that can cheat this functionality a bit, for example ProtoInput.

https://github.com/Ilyaki/ProtoInput/releases/tag/v1.1.2

Some antivirus programs may rate this program as potentially dangerous, in which case you need to add exclusions.

Start the program and follow these steps:
1. Switch to the MC instance you want to support when it is out of focus.
2. Return to the program and click the button "Add focused windows”
3. Make sure you have now selected instance in the top right corner and press “Inject instances”
Breaking blocks should work properly now.

If you want breaking blocks to work regardless of which instance is focused, repeat the same steps for the second instance.

Hope it helps some1!

**Comment by thesaltan1312** [comment]
Thank you for the detailed instructions to a possible fix, but this has
created new issues for me.

Tried as you directed, resulted in all inputs to the minecraft window being
locked, including mouse and keyboard inputs, forcing me to close the window.

Are there other steps that someone should take when using protoinput for
the first time? I noticed a few tick boxes under the inject instances
button that might have something to do with this behaviour but even after
disabling all of them the behaviour persisted.
